export type GlossaryCategory = "Mercado" | "Instrumentos" | "Ordens e execução" | "Análise técnica" | "Risco" | "Psicologia" | "Estatística" | "Macroeconomia";

export interface GlossaryEntry {
  slug: string;
  term: string;
  category: GlossaryCategory;
  /** one-sentence definition */
  definition: string;
  /** explained to a beginner */
  simple: string;
  technical: string;
  example: string;
  related: readonly string[];
}

const g = (slug: string, term: string, category: GlossaryCategory, definition: string, simple: string, technical: string, example: string, related: string[] = []): GlossaryEntry => ({ slug, term, category, definition, simple, technical, example, related });

export const GLOSSARY: readonly GlossaryEntry[] = [
  // ───────── Instrumentos e mercado
  g("trading", "Trading", "Mercado", "Comprar e vender instrumentos financeiros para lucrar com variações de preço.", "Tentar ganhar com as subidas e descidas do preço, em prazos curtos.", "Atividade de curto/médio prazo orientada à variação de preço, em contraste com o investimento de longo prazo orientado ao valor fundamental.", "Comprar o índice a 39.000 e vender a 39.040 é um trade de +40 pontos.", ["leverage", "risk-per-trade"]),
  g("index", "Índice (Index)", "Mercado", "Número calculado que resume o desempenho de um conjunto de ativos.", "Um 'termómetro' do mercado: não se compra diretamente, mas há produtos que o seguem.", "Calculado com uma metodologia (componentes e ponderação). Replicado por ETFs, futuros, opções e CFDs.", "O S&P 500 é ponderado por capitalização; o Dow Jones por preço.", ["djia", "us30", "price-weighted"]),
  g("djia", "Dow Jones Industrial Average (DJIA)", "Mercado", "Índice de 30 grandes empresas dos EUA, ponderado por preço.", "O 'Dow': 30 empresas americanas importantes.", "Criado em 1896. Soma dos preços das ações dividida por um divisor ajustado a splits e alterações. Calculado pela S&P Dow Jones Indices.", "Uma ação de $400 pesa 10× mais do que uma de $40, qualquer que seja a dimensão da empresa.", ["index", "price-weighted", "us30"]),
  g("price-weighted", "Ponderação por preço", "Mercado", "Método em que as ações de preço mais alto têm mais peso no índice.", "Quanto mais cara a ação, mais mexe com o índice.", "Característica do DJIA. Contrasta com a ponderação por capitalização bolsista (S&P 500, Nasdaq-100).", "Se uma ação de $400 sobe 1%, o efeito no Dow é muito maior do que uma de $40 a subir 1%.", ["djia", "index"]),
  g("us30", "US30", "Instrumentos", "Nome comum do CFD sobre o Dow Jones em muitas plataformas.", "É o Dow Jones, mas através de um CFD do teu broker.", "O símbolo varia por broker (US30, DJ30, WS30). Tamanho do contrato, spread, margem e horários dependem do broker.", "1 lote de US30 pode valer $1, $10 ou outro valor por ponto, consoante o broker.", ["cfd", "ym", "contract-size"]),
  g("nasdaq", "NASDAQ", "Mercado", "Bolsa eletrónica dos EUA, e nome usado para os índices Nasdaq Composite e Nasdaq-100.", "Uma bolsa com muitas empresas de tecnologia; o 'Nasdaq' costuma significar o Nasdaq-100.", "O Nasdaq-100 reúne as 100 maiores empresas não financeiras do NASDAQ, ponderado por capitalização (ajustada).", "Nos CFDs aparece como US100 ou NAS100; em futuros, NQ e MNQ.", ["index", "djia"]),
  g("cfd", "CFD (Contract for Difference)", "Instrumentos", "Contrato de diferença entre o preço de abertura e de fecho, com o broker como contraparte.", "Apostas na variação do preço sem possuíres o ativo.", "Derivado OTC alavancado. Custos: spread, swap overnight e, por vezes, comissão. Risco de contraparte e regulação por país (ESMA na UE).", "Compras 1 CFD a 39.000 e vendes a 39.040: ganhas 40 pontos × valor por ponto.", ["leverage", "margin", "spread", "us30"]),
  g("futures", "Futuros (Futures)", "Instrumentos", "Contratos padronizados, negociados em bolsa, para comprar/vender um ativo numa data futura.", "Contratos 'oficiais' com data de validade, negociados numa bolsa como o CME.", "Têm multiplicador, tick, mês de expiração e liquidação definidos pela bolsa. Marcação diária ao mercado e câmara de compensação.", "O YM é um futuro sobre o Dow: $5 por ponto, vencimentos trimestrais.", ["ym", "mym", "expiry", "margin"]),
  g("ym", "YM (E-mini Dow)", "Instrumentos", "Futuro E-mini sobre o Dow Jones: $5 por ponto do índice.", "O contrato 'normal' do Dow nos futuros do CME.", "CBOT/CME Group. Multiplicador $5; tick 1,00 ponto = $5,00; vencimentos trimestrais; liquidação em dinheiro (ver Learning Sources).", "Mover 40 pontos = 40 × $5 = $200 por contrato.", ["mym", "tick", "contract-size", "futures"]),
  g("mym", "MYM (Micro E-mini Dow)", "Instrumentos", "Futuro Micro sobre o Dow Jones: $0,50 por ponto, 1/10 do YM.", "A versão pequena do YM: serve para arriscar menos por contrato.", "Multiplicador $0,50; tick 1,00 ponto = $0,50. 10 MYM expõem o mesmo que 1 YM.", "Stop de 50 pontos: 1 MYM arrisca $25; 1 YM arrisca $250.", ["ym", "tick", "position-sizing"]),
  g("tick", "Tick", "Instrumentos", "Menor variação de preço permitida num instrumento.", "O 'degrau' mínimo do preço.", "No YM e no MYM, 1 tick = 1,00 ponto do índice.", "O YM passa de 39.000 para 39.001 — um tick, $5 por contrato.", ["tick-value", "point"]),
  g("point", "Ponto (Point)", "Instrumentos", "Uma unidade do valor do índice.", "Se o Dow vai de 39.000 para 39.050, subiu 50 pontos.", "O valor em dólares por ponto depende do contrato: YM $5, MYM $0,50, CFD variável.", "50 pontos × $5 × 1 YM = $250.", ["tick", "tick-value"]),
  g("tick-value", "Tick value", "Instrumentos", "Valor monetário de um tick por contrato.", "Quanto dinheiro vale cada 'degrau' do preço.", "YM: $5,00/tick; MYM: $0,50/tick.", "Stop de 40 ticks no MYM = $20 por contrato.", ["tick", "contract-size"]),
  g("contract-size", "Contract size", "Instrumentos", "Quanto vale cada ponto por contrato (multiplicador).", "O 'tamanho' do contrato: define quanto dinheiro mexe por ponto.", "Valor nocional = preço × multiplicador × contratos.", "A 39.000, 1 YM tem nocional de $195.000; 1 MYM, $19.500.", ["notional", "tick-value"]),
  g("notional", "Valor nocional", "Instrumentos", "Exposição total de uma posição: preço × multiplicador × contratos.", "O valor 'real' que estás a controlar, muito maior que a margem.", "A base para medir alavancagem efetiva (nocional ÷ saldo).", "3 MYM a 39.000 = $58.500 de nocional.", ["leverage", "contract-size"]),
  g("expiry", "Expiração (Expiry)", "Instrumentos", "Data em que um contrato de futuros deixa de ser negociado.", "A 'data de validade' do contrato.", "Os futuros de índices têm ciclo trimestral (março, junho, setembro, dezembro). Quem quer manter exposição faz rollover.", "O contrato de dezembro substitui o de setembro quando este expira.", ["rollover", "front-month"]),
  g("rollover", "Rollover", "Instrumentos", "Passagem de uma posição do contrato que expira para o seguinte.", "Mudar do contrato 'velho' para o 'novo' antes do fim.", "Fecha-se o contrato atual e abre-se o seguinte; a diferença de preço entre eles (spread de calendário) é um custo/ajuste.", "Em setembro, rolar de ‘Sep’ para ‘Dec’.", ["expiry", "front-month", "continuous-contract"]),
  g("front-month", "Front month", "Instrumentos", "O contrato com o vencimento mais próximo (normalmente o mais líquido).", "O contrato 'da vez': o que está mais perto do vencimento e onde normalmente está a maior parte do volume.", "Concentra a maior parte do volume até se aproximar a expiração.", "Em agosto, o front month do YM é o de setembro.", ["expiry", "rollover"]),
  g("continuous-contract", "Contrato contínuo", "Instrumentos", "Série de preços que junta vários contratos para formar um histórico contínuo.", "Um gráfico 'emendado' de vários contratos.", "Pode ser ajustado por diferença (back-adjusted) ou não; os níveis históricos podem diferir dos preços reais da época.", "O gráfico YM1! de uma plataforma é um contínuo.", ["rollover"]),
  g("globex", "Globex", "Mercado", "Plataforma eletrónica de negociação do CME, quase 24 horas por dia.", "O mercado eletrónico 'sempre aberto' do CME (com pausa diária).", "Horários, pausas e feriados devem ser confirmados no CME (ver Learning Sources).", "Os futuros do Dow negociam fora do horário do cash market dos EUA.", ["rth", "pre-market"]),
  g("rth", "RTH (Regular Trading Hours)", "Mercado", "Horário regular do mercado cash dos EUA: 09:30–16:00 ET.", "O horário 'normal' da bolsa de Nova Iorque.", "Em RTH há mais volume e volatilidade nos índices americanos; fora dele fala-se em sessão estendida.", "A abertura às 09:30 ET costuma ter volatilidade elevada.", ["pre-market", "post-market", "globex"]),
  g("pre-market", "Pré-mercado", "Mercado", "Período antes da abertura do mercado regular.", "O que acontece antes das 09:30 ET.", "Menor liquidez e spreads mais largos; notícias podem mover o preço.", "Dados económicos às 08:30 ET saem no pré-mercado.", ["rth", "post-market"]),
  g("post-market", "Pós-mercado", "Mercado", "Período depois do fecho do mercado regular.", "O que acontece depois das 16:00 ET.", "Resultados de empresas costumam sair aqui; liquidez reduzida.", "Uma empresa do Dow reporta às 16:05 ET e o futuro reage.", ["rth", "pre-market"]),
  g("liquidity", "Liquidez (Liquidity)", "Mercado", "Facilidade de comprar/vender sem mover muito o preço; também zonas onde há ordens (stops) concentradas.", "Quanta gente há para negociar contigo ao preço atual — e onde estão os stops de todos.", "Dois sentidos: (1) profundidade do mercado; (2) conceito de análise: zonas com stops acumulados (equal highs/lows, máximos do dia) que o preço pode ir buscar.", "O YM é muito líquido em RTH; fora de horas, o spread pode alargar.", ["equal-highs-lows", "liquidity-sweep", "slippage"]),
  // ───────── Ordens e execução
  g("bid", "Bid", "Ordens e execução", "Melhor preço a que há quem queira comprar.", "O preço a que consegues vender.", "O lado comprador do livro de ordens.", "Bid 39.000: se vendes a mercado, vendes a 39.000.", ["ask", "spread"]),
  g("ask", "Ask (Offer)", "Ordens e execução", "Melhor preço a que há quem queira vender.", "O preço a que consegues comprar.", "O lado vendedor do livro de ordens.", "Ask 39.001: se compras a mercado, pagas 39.001.", ["bid", "spread"]),
  g("spread", "Spread", "Ordens e execução", "Diferença entre o ask e o bid.", "O 'custo de entrada': começas ligeiramente a perder.", "Nos CFDs é definido pelo broker e pode alargar em notícias; nos futuros resulta do mercado.", "Bid 39.000,0 / ask 39.001,5 → spread de 1,5 pontos.", ["bid", "ask", "slippage"]),
  g("commission", "Comissão", "Ordens e execução", "Valor cobrado pela execução, normalmente por contrato e por lado.", "A 'taxa' que pagas por cada ordem executada — pequena, mas soma ao longo do tempo.", "Nos futuros somam-se taxas de bolsa e regulatórias. Round turn = entrada + saída.", "$2,50 por lado → $5,00 round turn por contrato.", ["spread", "slippage"]),
  g("slippage", "Slippage", "Ordens e execução", "Diferença entre o preço esperado e o preço de execução.", "Executar a um preço pior (ou melhor) do que querias.", "Mais provável em ordens stop, notícias e baixa liquidez. Inclui-se nas estimativas de risco.", "Stop em 38.950 executado a 38.944: 6 pontos de slippage.", ["stop-order", "liquidity"]),
  g("market-order", "Ordem a mercado", "Ordens e execução", "Executa de imediato ao melhor preço disponível.", "Compras/vendes já, ao preço que estiver.", "Garante (quase) execução, não o preço.", "Compra a mercado com ask 39.001 → entras a 39.001 ou pior.", ["limit-order", "slippage"]),
  g("limit-order", "Ordem limite", "Ordens e execução", "Executa apenas ao preço indicado ou melhor.", "Só compras/vendes se o preço chegar ao que definiste.", "Garante preço, não execução.", "Buy limit a 39.000 com o preço em 39.050.", ["market-order", "take-profit"]),
  g("stop-order", "Ordem stop", "Ordens e execução", "Ordem ativada quando o preço toca um nível; depois executa a mercado (ou limite).", "Uma ordem 'adormecida' que acorda quando o preço lá chega.", "Stop-market: garante saída, não preço. Stop-limit: garante limite, não saída.", "Sell stop em 38.950 para proteger um long.", ["stop-loss", "slippage"]),
  g("stop-loss", "Stop Loss (SL)", "Ordens e execução", "Ordem que fecha a posição quando a ideia fica invalidada.", "A tua saída 'de emergência' pré-definida.", "Deve ficar num nível técnico; define o risco por contrato e, com ele, o tamanho da posição.", "Long a 39.000 com SL em 38.950 → 50 pontos de risco.", ["take-profit", "position-sizing", "invalidation"]),
  g("take-profit", "Take Profit (TP)", "Ordens e execução", "Ordem limite que fecha a posição com lucro num alvo definido.", "O teu alvo de lucro, definido antes de entrar no trade.", "Deve ter sentido técnico e espaço livre até lá; relaciona-se com o R:R.", "Entrada 39.000, TP 39.100 → 100 pontos de alvo.", ["stop-loss", "r-multiple", "limit-order"]),
  g("margin", "Margem (Margin)", "Ordens e execução", "Depósito de garantia exigido para abrir e manter uma posição alavancada.", "O dinheiro 'preso' como garantia — não é o preço do contrato.", "Inicial e de manutenção; definida pela bolsa e pelo broker; muda com a volatilidade. Não limita a perda.", "Margem ilustrativa de $9.000 para 1 YM (nocional $195.000).", ["leverage", "margin-call", "notional"]),
  g("margin-call", "Margin call", "Ordens e execução", "Aviso (ou liquidação) quando o saldo cai abaixo da margem de manutenção.", "O broker diz: 'põe mais dinheiro ou fechamos as tuas posições'.", "Pode levar a liquidação forçada ao pior preço possível.", "Equity abaixo da margem de manutenção → posições fechadas.", ["margin", "drawdown"]),
  g("leverage", "Alavancagem (Leverage)", "Ordens e execução", "Relação entre a exposição (nocional) e o capital que a suporta.", "Controlar muito com pouco — o que amplia ganhos e perdas.", "Alavancagem = nocional ÷ margem (ou ÷ saldo, na versão efetiva).", "Nocional $195.000 numa conta de $10.000 = 19,5×.", ["margin", "notional", "drawdown"]),
  g("equity", "Equity", "Ordens e execução", "Saldo da conta mais o P&L das posições abertas.", "O valor da conta 'ao vivo'.", "Equity = balance + P&L aberto. Usada para margem e drawdown.", "Balance $10.000 e posição a ganhar $150 → equity $10.150.", ["balance", "drawdown"]),
  g("balance", "Balance", "Ordens e execução", "Saldo realizado: capital inicial mais resultados fechados.", "O dinheiro da conta sem contar posições abertas.", "Só muda quando fechas posições.", "Fechar um trade com +$100 aumenta o balance em $100.", ["equity"]),
  // ───────── Análise técnica
  g("ohlc", "OHLC", "Análise técnica", "Open, High, Low, Close: os quatro preços de um candle.", "Abertura, máximo, mínimo e fecho de cada período.", "Base dos gráficos de candles e barras.", "Candle M15: O 39.000, H 39.040, L 38.990, C 39.030.", ["candlestick", "body", "wick"]),
  g("candlestick", "Candle", "Análise técnica", "Representação gráfica do OHLC de um período.", "Uma 'vela' que mostra o que o preço fez naquele período.", "Corpo entre open e close; pavios até high e low. Bullish se close > open.", "Candle verde = fechou acima da abertura.", ["ohlc", "body", "wick"]),
  g("body", "Corpo (Body)", "Análise técnica", "Parte do candle entre a abertura e o fecho.", "A parte 'grossa' do candle.", "Corpos grandes sugerem convicção; pequenos, indecisão.", "Corpo de 60 pontos vs. pavios de 10.", ["wick", "candlestick"]),
  g("wick", "Pavio (Wick/Shadow)", "Análise técnica", "Linha fina entre o corpo e o high/low do candle.", "Até onde o preço foi e voltou.", "Pavios longos mostram rejeição de preços.", "Pavio inferior longo após um mínimo.", ["body", "rejection"]),
  g("bullish-bearish", "Bullish / Bearish", "Análise técnica", "Bullish: viés ou candle de alta. Bearish: viés ou candle de baixa.", "Bullish = a favor da subida; bearish = a favor da descida.", "Aplica-se a candles, estruturas, tendências e vieses.", "Estrutura bullish: HH e HL.", ["trend", "market-structure"]),
  g("pin-bar", "Pin bar", "Análise técnica", "Candle com pavio longo e corpo pequeno que mostra rejeição.", "O preço foi longe, mas voltou.", "Só tem significado em contexto (nível, estrutura); isolada é apenas informação.", "Pin bar de alta num suporte após um pullback.", ["rejection", "engulfing"]),
  g("engulfing", "Engulfing", "Análise técnica", "Candle cujo corpo engloba o do candle anterior.", "Um candle 'engole' o anterior.", "Sinal de mudança de controlo no curto prazo — sempre dependente do contexto.", "Engulfing bullish que fecha acima do corpo do candle anterior.", ["pin-bar", "confirmation"]),
  g("inside-bar", "Inside bar", "Análise técnica", "Candle contido dentro do range do candle anterior.", "Uma pausa de indecisão: o mercado ficou dentro do intervalo do candle anterior.", "Pode anteceder continuação ou rompimento; não prevê a direção.", "High e low dentro do candle-mãe.", ["breakout", "consolidation"]),
  g("rejection", "Rejeição", "Análise técnica", "Reação em que o preço toca um nível e é empurrado de volta.", "O mercado diz 'não' a esse preço.", "Visível como pavios longos e fechos longe do extremo.", "Máximos repetidos rejeitados em 38.600.", ["wick", "support", "resistance"]),
  g("trend", "Tendência (Trend)", "Análise técnica", "Direção dominante do preço ao longo do tempo.", "Para onde o preço tem andado: cima, baixo ou de lado.", "Em termos de estrutura: bullish (HH/HL), bearish (LH/LL) ou lateral.", "Dow a fazer máximos e mínimos cada vez mais altos = tendência de alta.", ["market-structure", "range"]),
  g("market-structure", "Market structure", "Análise técnica", "Sequência de swings (máximos e mínimos) que descreve o comportamento do preço.", "O 'esqueleto' do gráfico: onde estão os máximos e mínimos importantes.", "Bullish: HH/HL. Bearish: LH/LL. A quebra do último HL/LH sinaliza mudança de estrutura.", "HL em 38.430 quebrado → estrutura deixa de ser bullish.", ["swing-high", "swing-low", "hh-hl-lh-ll"]),
  g("swing-high", "Swing high", "Análise técnica", "Máximo local: mais alto do que os vizinhos.", "Um 'topo' no gráfico: um ponto mais alto do que os vizinhos, onde o preço virou para baixo.", "Definição prática: high superior aos N candles antes e depois.", "Topo em 38.600 após subida.", ["swing-low", "market-structure"]),
  g("swing-low", "Swing low", "Análise técnica", "Mínimo local: mais baixo do que os vizinhos.", "Um 'fundo' no gráfico: um ponto mais baixo do que os vizinhos, onde o preço virou para cima.", "Low inferior aos N candles antes e depois.", "Fundo em 38.300 antes da recuperação.", ["swing-high", "market-structure"]),
  g("hh-hl-lh-ll", "HH / HL / LH / LL", "Análise técnica", "Higher High, Higher Low, Lower High, Lower Low.", "Máximo mais alto, mínimo mais alto, máximo mais baixo, mínimo mais baixo.", "Rótulos que comparam cada swing com o anterior do mesmo tipo.", "Um máximo em 38.620 depois de um anterior em 38.420 é um HH (+200 pontos acima).", ["market-structure", "trend"]),
  g("range", "Range (lateralização)", "Análise técnica", "Mercado que oscila entre um suporte e uma resistência sem tendência clara.", "O preço anda de lado numa 'caixa'.", "Swings sobrepostos e sinais mistos de estrutura; rompimentos podem ser falsos.", "Dow entre 38.200 e 38.500 durante horas.", ["consolidation", "breakout"]),
  g("consolidation", "Consolidação", "Análise técnica", "Fase de compressão do preço antes de um novo movimento.", "O preço 'respira' num intervalo curto.", "Menor volatilidade e candles pequenos; pode resolver-se em continuação ou reversão.", "Barras pequenas durante 40 minutos.", ["range", "breakout"]),
  g("support", "Suporte", "Análise técnica", "Zona onde a procura tem travado quedas.", "Um 'chão' onde o preço costuma parar.", "Zona (não linha) com múltiplos toques; pode falhar.", "Mínimos repetidos em 38.300.", ["resistance", "sr-flip", "demand"]),
  g("resistance", "Resistência", "Análise técnica", "Zona onde a oferta tem travado subidas.", "Um 'teto' onde o preço costuma parar.", "Zona com múltiplas rejeições; pode ser rompida.", "Máximos repetidos em 38.600.", ["support", "sr-flip", "supply"]),
  g("sr-flip", "Suporte vira resistência (e vice-versa)", "Análise técnica", "Um nível rompido passa a funcionar na função oposta.", "O teto de ontem pode ser o chão de hoje.", "Frequente em retestes; não é garantido.", "Resistência em 38.300 rompida e retestada como suporte.", ["support", "resistance", "retest"]),
  g("supply", "Oferta (Supply)", "Análise técnica", "Zona de origem de um movimento de descida impulsivo, onde vendedores dominaram.", "Onde havia muitos vendedores antes de uma queda forte.", "Base + saída impulsiva; fresca, testada ou invalidada. Não garante reversão.", "Pequena consolidação antes de queda de 300 pontos.", ["demand", "imbalance"]),
  g("demand", "Procura (Demand)", "Análise técnica", "Zona de origem de uma subida impulsiva, onde compradores dominaram.", "Onde havia muitos compradores antes de uma subida forte.", "Base + saída impulsiva para cima.", "Consolidação em 38.300 antes de subir 320 pontos.", ["supply", "imbalance"]),
  g("imbalance", "Imbalance", "Análise técnica", "Movimento rápido e unidirecional que deixa pouca negociação para trás.", "Um movimento tão rápido que quase não houve 'negócio' dos dois lados.", "Alguns traders estudam se o preço regressa a esses movimentos; não é garantido.", "Três candles grandes seguidos sem sobreposição.", ["supply", "demand", "displacement"]),
  g("fibonacci", "Fibonacci", "Análise técnica", "Conjunto de rácios (23,6%, 38,2%, 61,8%…) usados para medir correções e objetivos.", "Régua para medir quanto o preço recuou e até onde pode ir.", "Retracement: B − r·(B−A). Extension: A + r·(B−A). Projection: C + r·(B−A). Alguns níveis (70,7; 78,6; 88,6; 127,2; 141,4) derivam de raízes quadradas.", "Impulso 37.950→38.550: 61,8% = 38.179.", ["retracement", "extension", "projection"]),
  g("retracement", "Retracement", "Análise técnica", "Correção parcial de um impulso anterior.", "Quanto do movimento anterior o preço devolveu.", "Medido como percentagem do impulso A→B.", "Pullback que recua 50% de 600 pontos = 300 pontos.", ["fibonacci", "pullback"]),
  g("extension", "Extension", "Análise técnica", "Níveis para além do fim do impulso, medidos a partir do início (A).", "Até onde o movimento pode estender-se.", "Preço = A + r·(B−A), com r > 1.", "A=37.950, B=38.550, r=1,272 → 38.713.", ["fibonacci", "projection"]),
  g("projection", "Projection", "Análise técnica", "Projeção da perna AB a partir do ponto C.", "Repetir o tamanho do primeiro movimento a partir do fim da correção.", "Preço = C + r·(B−A). r = 1 é 'AB = CD'.", "C=38.180 → 38.780 com r=1.", ["fibonacci", "extension"]),
  g("pullback", "Pullback", "Análise técnica", "Recuo temporário contra a tendência dominante.", "Uma pausa/correção dentro de uma tendência.", "Setup clássico: tendência → pullback → nível → confluência → confirmação.", "Dow sobe 300 pontos e recua 150.", ["retracement", "continuation"]),
  g("continuation", "Continuação", "Análise técnica", "Retoma do movimento na direção da tendência anterior.", "A tendência continua depois de uma pausa.", "Padrão frequente após pullbacks ou consolidações.", "Rompimento da consolidação a favor da tendência.", ["pullback", "reversal"]),
  g("reversal", "Reversão", "Análise técnica", "Mudança da direção dominante.", "A tendência vira: o que subia passa a descer, ou ao contrário.", "Costuma exigir quebra de estrutura e confirmação.", "LH + LL após uma tendência de alta.", ["market-structure", "continuation"]),
  g("breakout", "Breakout (rompimento)", "Análise técnica", "Movimento do preço para fora de uma zona de suporte/resistência ou range.", "O preço 'sai da caixa' (da zona onde andava preso) e ganha uma nova direção.", "Pode ser válido ou falso; fecho acima/abaixo e reteste ajudam a avaliar.", "Fecho acima de 38.600 com volume.", ["fake-breakout", "retest"]),
  g("fake-breakout", "Falso rompimento", "Análise técnica", "Rompimento que falha e reverte para dentro da zona.", "O preço sai da caixa e volta logo.", "Frequente junto a liquidez (stops acumulados).", "Rompe 38.600 e fecha novamente abaixo.", ["breakout", "liquidity-sweep"]),
  g("retest", "Reteste", "Análise técnica", "Regresso do preço a um nível rompido para o testar.", "Voltar a 'tocar' o nível que acabou de ser rompido.", "Setup 'breakout + retest'.", "Rompe 38.300 e volta a testá-lo como suporte.", ["breakout", "sr-flip"]),
  g("equal-highs-lows", "Equal highs / equal lows", "Análise técnica", "Máximos ou mínimos praticamente iguais, formando um nível óbvio.", "Dois topos (ou fundos) à mesma altura.", "Marcam zonas onde se podem acumular stops (liquidez).", "Dois mínimos em 38.450 e 38.455.", ["liquidity", "liquidity-sweep"]),
  g("liquidity-sweep", "Liquidity sweep", "Análise técnica", "Movimento que ultrapassa brevemente um nível óbvio e reverte.", "O preço vai 'buscar' os stops e volta.", "Descrição de um comportamento observável no gráfico; não prova intenção de ninguém.", "Rompe equal lows e fecha de volta acima.", ["liquidity", "fake-breakout"]),
  g("displacement", "Displacement", "Análise técnica", "Movimento forte e rápido numa direção.", "Um 'empurrão' grande do preço.", "Candles grandes com pouca sobreposição; indica momentum.", "Três candles consecutivos de 80 pontos.", ["momentum", "imbalance"]),
  g("momentum", "Momentum", "Análise técnica", "Força e velocidade do movimento do preço.", "Quão 'à pressa' o preço anda.", "Pode ser avaliado por candles grandes, ATR crescente ou indicadores.", "ATR a subir com candles direcionais.", ["displacement", "exhaustion"]),
  g("exhaustion", "Exaustão", "Análise técnica", "Perda de força de um movimento prolongado.", "O movimento 'cansa': continua, mas cada vez com menos força.", "Sinais: candles menores, pavios de rejeição, divergências. Não prevê reversão certa.", "Subida de 600 pontos termina com pavios longos.", ["momentum", "reversal"]),
  g("confluence", "Confluência", "Análise técnica", "Coincidência de várias razões independentes no mesmo ponto.", "Várias 'provas' a apontar para o mesmo sítio.", "Educativamente, o Confluence Score soma +1 por fator (máx. 8). Não garante resultado.", "Estrutura + suporte + Fibonacci + confirmação.", ["confirmation", "market-structure"]),
  g("confirmation", "Confirmação", "Análise técnica", "Evidência adicional de que a ideia está a funcionar antes de entrar.", "Esperar um sinal de que o preço reage.", "Ex.: candle de rejeição com fecho, quebra de micro-estrutura.", "Engulfing bullish no nível.", ["confluence", "invalidation"]),
  g("invalidation", "Invalidação", "Análise técnica", "Nível ou condição em que a ideia deixa de ser válida.", "O ponto em que admites 'estava errado'.", "Define o stop e a pergunta 'o que invalidaria a minha tese?'.", "Fecho abaixo do último HL.", ["stop-loss"]),
  g("atr", "ATR (Average True Range)", "Análise técnica", "Média do intervalo verdadeiro: mede a volatilidade típica por candle.", "Quanto o preço costuma andar por candle.", "Calculado com suavização (período típico 14). Útil para dimensionar stops.", "ATR M15 de 46 pontos → stop de 1,5×ATR ≈ 69 pontos.", ["volatility", "adx"]),
  g("adx", "ADX", "Análise técnica", "Indicador que mede a força (não a direção) de uma tendência.", "Diz se há tendência forte, não para onde vai.", "Média Direcional; valores mais altos indicam tendência mais forte. Indicador atrasado.", "ADX acima de 25 é frequentemente lido como tendência forte (convenção).", ["trend", "atr"]),
  g("volatility", "Volatilidade", "Análise técnica", "Medida da amplitude das oscilações do preço.", "O quão 'nervoso' está o mercado.", "Mede-se por ATR, desvio-padrão, VIX (para o S&P). Aumenta em notícias e aberturas.", "Abertura de NY costuma ter volatilidade acima da média.", ["atr", "slippage"]),
  g("moving-average", "Média móvel", "Análise técnica", "Média dos últimos N preços, atualizada a cada candle.", "Uma linha que suaviza o preço.", "SMA (simples) ou EMA (exponencial). Indicador atrasado.", "SMA 50 como referência dinâmica.", ["trend"]),
  g("pdh-pdl", "PDH / PDL", "Análise técnica", "Previous Day High / Low: máximo e mínimo do dia anterior.", "Os extremos de ontem: o ponto mais alto e o mais baixo do dia anterior.", "Níveis de referência comuns; atraem reações e liquidez.", "Preço aproxima-se do PDH às 15:00.", ["pwh-pwl", "liquidity"]),
  g("pwh-pwl", "PWH / PWL", "Análise técnica", "Previous Week High / Low: máximo e mínimo da semana anterior.", "Os extremos da semana passada.", "Níveis de referência de prazo mais longo.", "Rompimento do PWH numa segunda-feira.", ["pdh-pdl"]),
  g("opening-range", "Opening range", "Análise técnica", "Intervalo de preços nos primeiros minutos da sessão.", "Onde o preço andou ao início do dia.", "Comum: primeiros 15 ou 30 minutos após a abertura do cash market.", "Opening range 09:30–10:00 ET de 120 pontos.", ["rth", "gap"]),
  g("gap", "Gap", "Análise técnica", "Diferença entre o fecho anterior e a abertura seguinte.", "O preço 'salta' de um nível para outro.", "Em futuros 24h, os gaps surgem sobretudo após pausas e fins de semana.", "Abre 80 pontos acima do fecho de sexta.", ["opening-range"]),
  g("trend-day", "Trend day", "Análise técnica", "Dia em que o preço se move numa direção quase todo o dia.", "Um dia 'de tendência': o preço anda numa só direção quase sem recuos.", "Menos retrocessos; stops de reversão sofrem.", "Dow sobe de forma contínua da abertura ao fecho.", ["range-day"]),
  g("range-day", "Range day", "Análise técnica", "Dia em que o preço oscila numa faixa sem direção clara.", "Um dia 'de lado': o preço oscila numa faixa sem decidir para onde vai.", "Rompimentos falham com frequência.", "Dow preso 150 pontos todo o dia.", ["trend-day", "range"]),
  // ───────── Macro
  g("cpi", "CPI", "Macroeconomia", "Índice de Preços no Consumidor: mede a inflação ao consumidor.", "A inflação dos preços que pagamos.", "Publicado mensalmente pelo BLS. Influencia expectativas de taxas de juro e, por isso, os índices.", "CPI acima do esperado pode aumentar a volatilidade.", ["ppi", "fomc"]),
  g("ppi", "PPI", "Macroeconomia", "Índice de Preços no Produtor: inflação na produção.", "A inflação 'à saída da fábrica'.", "Publicado pelo BLS; indicador antecedente da inflação.", "PPI e CPI saem em dias próximos.", ["cpi"]),
  g("nfp", "NFP (Non-Farm Payrolls)", "Macroeconomia", "Relatório mensal de emprego não agrícola nos EUA.", "Quantos empregos foram criados.", "Parte do relatório Employment Situation (BLS), tipicamente à sexta-feira às 08:30 ET.", "NFP muito acima/abaixo do esperado alarga spreads.", ["unemployment", "jobless-claims"]),
  g("fomc", "FOMC", "Macroeconomia", "Comité de política monetária da Reserva Federal.", "Quem decide as taxas de juro dos EUA.", "Reúne-se várias vezes por ano; decisão, projeções e conferência de imprensa.", "Decisão às 14:00 ET seguida de conferência às 14:30 ET.", ["fed-funds", "cpi"]),
  g("fed-funds", "Fed Funds Rate", "Macroeconomia", "Taxa de juro de referência da política monetária dos EUA.", "O 'preço do dinheiro' nos EUA.", "Alterações influenciam avaliações de ações e o dólar.", "Aumento de 25 pontos-base.", ["fomc"]),
  g("unemployment", "Taxa de desemprego", "Macroeconomia", "Percentagem da força de trabalho sem emprego.", "Quantas pessoas procuram trabalho sem encontrar.", "Parte do relatório mensal de emprego.", "Subida inesperada para 4,5%.", ["nfp"]),
  g("gdp", "GDP / PIB", "Macroeconomia", "Produto Interno Bruto: valor da produção de uma economia.", "O tamanho da economia: tudo o que um país produziu num período.", "Divulgado trimestralmente pelo BEA em várias estimativas.", "Estimativa avançada do PIB do trimestre.", ["pmi"]),
  g("retail-sales", "Retail sales", "Macroeconomia", "Vendas a retalho: indicador do consumo.", "Quanto os consumidores gastaram.", "Publicado mensalmente; consumo é grande parte da economia dos EUA.", "Vendas acima do esperado.", ["gdp"]),
  g("pmi", "PMI", "Macroeconomia", "Índice de gestores de compras: pulso da indústria/serviços.", "Um 'termómetro' da atividade económica.", "Valores acima de 50 indicam expansão (convenção).", "Um ISM Manufacturing PMI em 52 indica expansão da atividade industrial.", ["gdp"]),
  g("jobless-claims", "Jobless claims", "Macroeconomia", "Pedidos semanais de subsídio de desemprego.", "Quantos pedidos de apoio ao desemprego foram feitos esta semana.", "Divulgado às quintas-feiras; indicador frequente e ruidoso.", "230 mil pedidos numa semana, ligeiramente acima do esperado.", ["nfp", "unemployment"]),
  // ───────── Risco / estatística / psicologia
  g("risk-per-trade", "Risco por trade", "Risco", "Valor (ou % da conta) que aceitas perder se o stop for atingido.", "Quanto estás disposto a perder neste trade.", "Define o tamanho da posição: risco ÷ risco por contrato.", "1% de uma conta de $10.000 = $100 de risco máximo por trade.", ["position-sizing", "stop-loss"]),
  g("position-sizing", "Position sizing", "Risco", "Cálculo do número de contratos a partir do risco e da distância ao stop.", "Quantos contratos podes usar sem arriscar mais do que planeaste.", "Contratos = floor(risco em $ ÷ (pontos até ao stop × valor por ponto + custos)).", "$100 de risco, stop 50 pts, MYM: 4 contratos.", ["risk-per-trade", "mym"]),
  g("r-multiple", "R-multiple", "Risco", "Resultado medido em múltiplos do risco inicial (R).", "Quantas vezes o risco ganhaste ou perdeste.", "R = pontos ganhos ÷ pontos arriscados.", "Ganhar 100 pontos com stop de 50 = +2R.", ["reward-risk", "expectancy"]),
  g("reward-risk", "R:R (Reward:Risk)", "Risco", "Relação entre o retorno potencial e o risco.", "Quanto podes ganhar por cada unidade arriscada.", "R:R = distância ao alvo ÷ distância ao stop. Taxa de acerto de equilíbrio = 1 ÷ (1 + R:R).", "Alvo a 100 pontos e stop a 50 pontos dá um R:R de 2:1.", ["r-multiple", "win-rate"]),
  g("drawdown", "Drawdown", "Risco", "Queda do pico de capital até ao ponto mais baixo seguinte.", "Quanto a conta caiu desde o seu máximo.", "Medido em $ ou %. Recuperação exige mais do que a perda (−50% pede +100%).", "Pico de $10.300, mínimo de $10.100 → drawdown de $200.", ["equity", "losing-streak"]),
  g("losing-streak", "Sequência de perdas", "Risco", "Várias perdas consecutivas.", "Perder vários trades seguidos.", "Inevitável estatisticamente; o risco por trade define se é suportável.", "10 perdas a 2% deixam ~82% da conta.", ["drawdown", "risk-per-trade"]),
  g("max-daily-loss", "Perda diária máxima", "Risco", "Limite de perda por dia, após o qual deixas de operar.", "O teu 'disjuntor' diário.", "Definido antes da sessão (ex.: 2–3% da conta).", "Com limite de $300 por dia, paras de operar assim que a perda do dia chegar a −$300.", ["drawdown", "revenge-trading"]),
  g("win-rate", "Win rate", "Estatística", "Percentagem de trades vencedores.", "Em quantos trades ganhas.", "Sozinho não diz nada: depende do R:R.", "40% de win rate com 3:1 é rentável (sem custos).", ["expectancy", "reward-risk"]),
  g("expectancy", "Expectancy", "Estatística", "Resultado médio esperado por trade.", "Quanto ganhas ou perdes, em média, por trade.", "E = win% × ganho médio − loss% × perda média. Em R: E[R].", "40% × 3R − 60% × 1R = +0,6R.", ["win-rate", "profit-factor", "r-multiple"]),
  g("profit-factor", "Profit factor", "Estatística", "Ganhos brutos divididos pelas perdas brutas.", "Quanto ganhas por cada $1 que perdes.", "Acima de 1 é positivo (antes de custos e com amostra suficiente).", "Ganhos $600 / perdas $400 = 1,5.", ["expectancy"]),
  g("backtest", "Backtest", "Estatística", "Teste de uma estratégia em dados históricos.", "Ver como a regra teria funcionado no passado.", "Sujeito a vieses (look-ahead, sobreajuste); amostra pequena engana.", "100 decisões registadas no Backtesting Lab.", ["overfitting", "expectancy"]),
  g("overfitting", "Sobreajuste (Overfitting)", "Estatística", "Ajustar demasiado uma estratégia ao passado.", "Regras tão 'à medida' do passado que falham no futuro.", "Muitos parâmetros e pouca amostra produzem resultados enganadores.", "Uma estratégia com 12 filtros afinados.", ["backtest"]),
  g("journal", "Journal", "Estatística", "Registo estruturado dos teus trades e do teu raciocínio.", "O teu 'diário' de trading.", "Permite estatísticas e revisão de processo.", "Registar setup, emoção, erro e lição.", ["expectancy", "process"]),
  g("process", "Processo", "Psicologia", "Sequência repetível de decisões: antes, durante e depois do trade.", "O 'como' decides, independentemente do resultado.", "Avaliado por checklist, risco e disciplina — não pelo P&L de um trade.", "Bom processo que perde continua a ser bom processo.", ["journal"]),
  g("fomo", "FOMO", "Psicologia", "Medo de perder um movimento.", "Entrar porque 'toda a gente está a ganhar' e não queres ficar de fora.", "Leva a entradas tardias, stops largos e R:R pior.", "Comprar depois de 300 pontos de subida.", ["revenge-trading", "overtrading"]),
  g("revenge-trading", "Revenge trading", "Psicologia", "Operar para recuperar uma perda recente.", "Querer 'vingar-te' do mercado.", "Quebra regras de risco e tamanho.", "Dobrar o tamanho depois de uma perda.", ["fomo", "max-daily-loss"]),
  g("overtrading", "Overtrading", "Psicologia", "Operar mais do que o plano permite.", "Fazer mais trades do que o teu plano permite, muitas vezes por tédio ou ansiedade.", "Aumenta custos e erros; tédio e ansiedade são gatilhos.", "20 trades num dia com plano de 3.", ["fomo", "journal"]),
  g("confirmation-bias", "Viés de confirmação", "Psicologia", "Procurar apenas informação que confirma a tua ideia.", "Ver só o que te dá razão.", "Combate-se com a pergunta 'o que invalidaria a minha tese?'.", "Ignorar que o último HL foi quebrado porque continuas convencido de que o preço vai subir.", ["invalidation"]),
];

const bySlug = new Map(GLOSSARY.map((g) => [g.slug, g]));

export function getGlossaryEntry(slug: string): GlossaryEntry | undefined {
  return bySlug.get(slug);
}

export const GLOSSARY_CATEGORIES: readonly GlossaryCategory[] = ["Mercado", "Instrumentos", "Ordens e execução", "Análise técnica", "Macroeconomia", "Risco", "Estatística", "Psicologia"];
